name: bihand

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python==3.8.5
  - pip=20.0.2
  - pytorch==1.8.1
  - torchvision==0.9.1
  - cudatoolkit==11.1.1
  - numpy>=1.18
  - matplotlib>=3.1.3
  - scipy>=0.19.1
  - pillow~=7.1.2
  - setuptools~=46.2.0
  - tqdm
  - pip:
      - chumpy==0.69
      - cython==0.29.19
      - opencv-python==4.2.0.34
      - opencv-contrib-python==4.2.0.34
      - opendr==0.78
      - termcolor==1.1.0
      - transforms3d==0.3.1
      - trimesh==3.9.1
      - pyrender==0.1.43
      - ./manopth/.
